# Generated by Django 3.0.7 on 2020-11-03 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(whitelist=['omnivector.solutions'])], verbose_name='email address'),
        ),
    ]
