# Generated by Django 3.1.4 on 2021-01-20 19:57

from django.db import migrations, models
import jobbergate_api.username_validation


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210104_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[jobbergate_api.username_validation.EmailDomainValidator()], verbose_name='email address'),
        ),
    ]
