# Generated by Django 3.0.7 on 2020-11-03 02:36

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201103_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[apps.user.models.JobbergateEmailValidator(whitelist=['omnivector.solutions'])], verbose_name='email address'),
        ),
    ]
