# Generated by Django 3.0.7 on 2020-08-25 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=255)),
                ('application_description', models.TextField(default=False)),
                ('application_location', models.CharField(default=False, max_length=255)),
                ('application_dir_listing', models.TextField(default=False)),
                ('application_dir_listing_acquired', models.BooleanField(default=False)),
                ('application_file', models.TextField(default=False)),
                ('application_config', models.TextField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'db_table': 'applications',
            },
        ),
    ]
