# Generated by Django 3.0.7 on 2020-08-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_file',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_description',
            field=models.TextField(default=False),
        ),
    ]
