# Generated by Django 3.0.7 on 2020-08-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200827_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_config',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_file',
            field=models.TextField(),
        ),
    ]
