# Generated by Django 3.0.7 on 2020-08-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200814_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_config',
            field=models.TextField(default=False),
        ),
    ]
