# Generated by Django 3.0.7 on 2020-10-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_application_application_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('applications | application | Can view application', 'Can view object'),), 'verbose_name': 'application', 'verbose_name_plural': 'applications'},
        ),
    ]
