# Generated by Django 3.1.8 on 2021-05-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20210104_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_identifier',
            field=models.CharField(default=None, max_length=255, unique=True, null=True),
            preserve_default=False,
        ),
    ]
