---
APPLICATION_LOCATION_BASE_PATH: ${ssm:/jobbergate-api/staging/APPLICATION_LOCATION_BASE_PATH}
STAGE: ${self:provider.stage}
DATABASE_PASS: ${ssm:/jobbergate-api/staging/DATABASE_PASS}
DATABASE_USER: ${ssm:/jobbergate-api/staging/DATABASE_USER}
DATABASE_NAME: ${ssm:/jobbergate-api/staging/DATABASE_NAME}
DATABASE_HOST:
  ? "Fn::GetAtt"
  :
    - AuroraInstance
    - Endpoint.Address
DATABASE_PORT:
  ? "Fn::GetAtt"
  :
    - AuroraInstance
    - Endpoint.Port
DATABASE_URI:
  Fn::Join:
  - ''
  - - "postgres://"
    - ${ssm:/jobbergate-api/staging/DATABASE_USER}
    - ":"
    - ${ssm:/jobbergate-api/staging/DATABASE_PASS}
    - "@"
    - Fn::GetAtt:
       - AuroraInstance
       - Endpoint.Address
    - ":"
    - Fn::GetAtt:
      - AuroraInstance
      - Endpoint.Port
    - "/"
    - ${ssm:/jobbergate-api/staging/DATABASE_NAME}
CLOUDFRONT_DOMAIN: !GetAtt AssetsDistribution.DomainName
