# Generated by Django 3.0.7 on 2020-08-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='slurm_job_id',
            field=models.TextField(default=''),
        ),
    ]
